### PR TITLE
Fix #11, #12 and #13 and add Travis CI tests

### LINKED ISSUE #11: Multiple block devices
First:  awesome script ... thanks for writing this!

For both backups and consolidation the script breaks the list of block_devices returned from "virsh domblklist" into block_device using:
for block_device in "$block_devices"; do
"for" will treat "$block_devices" (in quotes) as a single argument and assign all of the block devices to $block_device.  I think what you meant was (no quotes):
    for block_device in $block_devices; do

For example (with quotes):
    # for i in "a b c"; do printf "arg: $i\n"; done
Returns:
    "arg: a b c"

Where (without quotes):
    # for i in a b c; do printf "arg: $i\n"; done
Returns:
    arg: a
    arg: b
    arg: c

### PR DESCRIPTION
**Pull request by dguerri**

### CODE REVIEW

**Comment by svorobyov** [comment]
I cannot manage this useless github web interface: no buttons except "comment" can be clicked.

Anyway, I assume you want me to test the development branch: 

git clone -b development https://github.com/dguerri/LibVirtKvm-scripts.git

**Comment by dguerri** [comment]
yes, exactly.

**Comment by svorobyov** [comment]
Snapshotting and backup worked OK for 2 single-disk and 1 dual-disk VMs.

Now testing live consolidation. Takes some time...

**Comment by dguerri** [comment]
Merged! Thank you so much @svorobyov for having beta-tested the development branch.

**Pull request merged**
