### PR TITLE
Add offline backup feature

### PR DESCRIPTION
**Pull request by AJRepo**
This commit iterates through all domains and determines which are online and
which are offline. It then adds an offline backup strategy using "cp -up" to
back up images and backing files.

### CODE REVIEW

**Comment by AJRepo** [comment]
I chose "cp -up" instead of rsync since cp is more universal and because in theory the snapshots shouldn't change at all. 

The travis-ci checks failed due to it's own connection issues ( W: Failed to fetch http://mirrors.kernel.org/ubuntu/dists/utopic/main/source/Sources  404  Not Found [IP: 2620:3:c000:a:0:1994:3:14 80] ) not script errors.

**Comment by dguerri** [comment]
Hi @AJRepo, that's awesome!
Could you just add a quick test to the travis-ci configuration file?

**Comment by AJRepo** [comment]
I haven't used travis-ci before. Let me know if that works. Also fixed issue with spaces in filenames and directories in the "cp" command.

**Comment by dguerri** [comment]
Thanks @AJRepo it seems ok!
I just need to fix that nasty issue with utopic repo address... I am moving home currently so it could take some time. Sorry:(

**Comment by AJRepo** [comment]
I tried a few different things to get the travis-CI thing to work. Apparently you need version > trusty to have shellcheck be in a repo and I didn't get vivid to upgrade even with --force-yes as it waits for confirmation about upgrading an init file. So I just ran shellcheck locally and updated fi-backup.sh (commit  5100d57) as per its recommendations.

**Comment by AJRepo** [comment]
Well - I got shellcheck to be deployed in trusty via cabal in the travis.yml 

But virt-install fails in the Travis-CI VM

<code>
$ sudo virt-install --connect qemu:///system --os-type linux --os-variant generic --debug --import --name t1d --ram 512 --vcpus 1 --noautoconsole --nographics --virt-type qemu --nonetworks --disk path=/tmp/test\ disks/test1\ 1.img,device=disk,format=qcow2

  [Fri, 16 Oct 2015 16:13:39 virt-install 390] DEBUG (cli:227) Launched with command line:
/usr/bin/virt-install --connect qemu:///system --os-type linux --os-variant generic --debug --import --name t1d --ram 512 --vcpus 1 --noautoconsole --nographics --virt-type qemu --nonetworks --disk path=/tmp/test disks/test1 1.img,device=disk,format=qcow2

[Fri, 16 Oct 2015 16:13:40 virt-install 390] DEBUG (cli:332) Requesting libvirt URI qemu:///system

[Fri, 16 Oct 2015 16:13:40 virt-install 390] ERROR (cli:445) Cannot recv data: Connection reset by peer

[Fri, 16 Oct 2015 16:13:40 virt-install 390] DEBUG (cli:448) 
Traceback (most recent call last):
  File "/usr/bin/virt-install", line 1014, in <module>
    sys.exit(main())
  File "/usr/bin/virt-install", line 994, in main
    conn = cli.getConnection(options.connect)
  File "/usr/lib/python2.7/dist-packages/virtinst/cli.py", line 333, in getConnection
    conn = open_connection(uri)
  File "/usr/lib/python2.7/dist-packages/virtinst/cli.py", line 348, in open_connection
    open_flags)
  File "/usr/lib/python2.7/dist-packages/libvirt.py", line 105, in openAuth
    if ret is None:raise libvirtError('virConnectOpenAuth() failed')
libvirtError: Cannot recv data: Connection reset by peer
</code>

So I'm stuck with what do do with the travis.yml file. 

The fi-backup.sh file as I've updated it passes all the tests in the travis.yml file locally and the shellcheck script as well as now being used here for my own backups.

**Comment by AJRepo** [comment]
Done. Fixed the build issue as well as timing issues preventing the rest of the script from completing.

**Comment by dguerri** [comment]
That's just awesome. Thanks!

**Pull request merged**
